env: local
#storage_path: "./storage/storage.db"
# fixme: rename to dsn
storage_path: "postgres://sdai-calculator:sdai-calculator@localhost:5432/sdai-calculator?sslmode=disable"
http_server:
  address: localhost:8080
  timeout: 4s
  idle_timeout: 60s